spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order-service}
    username: ${DB_USERNAME:eventshop}
    password: ${DB_PASSWORD:eventshop}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8083}

product-catalog:
  base-url: ${PRODUCT_CATALOG_URL:http://localhost:8081}

user-service:
  jwk-set-uri: ${USER_SERVICE_JWK_SET_URI:http://localhost:8082/oauth2/jwks}
  issuer: ${USER_SERVICE_ISSUER:http://localhost:8082}
  audience: ${USER_SERVICE_AUDIENCE:storeapp-api}
