spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order-service}
    username: ${DB_USERNAME:eventshop}
    password: ${DB_PASSWORD:eventshop}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

server:
  port: ${SERVER_PORT:8083}

product-catalog:
  base-url: ${PRODUCT_CATALOG_URL:http://localhost:8081}

user-service:
  jwk-set-uri: ${USER_SERVICE_JWK_SET_URI:http://localhost:8082/oauth2/jwks}
  issuer: ${USER_SERVICE_ISSUER:http://localhost:8082}
  audience: ${USER_SERVICE_AUDIENCE:storeapp-api}

messaging:
  order-events-topic: ${ORDER_EVENTS_TOPIC:order-events}
